import { useEffect, useMemo, useState } from 'react';
import AnalysisLoadingPage from './AnalysisLoading';
import DashboardExperience from './DashboardExperience';
import type { BusinessDraft, ProductDraft, SetupDraft } from './types';

const categories = ['Fashion', 'F&B', 'Beauty', 'Tech Services', 'Retail'];
const frequencies = ['Daily', '2-3 Times a Week', 'Weekly', 'Occasionally'];
const assistanceOptions = ['Content Calendar', 'Captions & Copy', 'Image Generation', 'Audience Engagement'];
const platforms = ['Facebook Page', 'Instagram', 'TikTok', 'Messenger', 'Viber', 'Telegram', 'Website', 'Google Business'];
const createProduct = (): ProductDraft => ({ id: crypto.randomUUID(), name: 'Premium Arabica Blend', category: 'Coffee Beans', price: '25000', usp: 'Locally sourced from Shan State', images: [] });
const initialBusiness: BusinessDraft = { businessName: 'Royal Rangoon Coffee', category: 'F&B', description: 'A premium Myanmar coffee brand serving authentic local beans.', brandVoice: ['Premium'], products: [createProduct()] };
const initialSetup: SetupDraft = { connectedPlatforms: ['Facebook Page'], postingFrequency: '2-3 Times a Week', assistance: ['Captions & Copy', 'Audience Engagement'] };
type AppScreen = 'signup' | 'step1' | 'step2' | 'analyzing' | 'dashboardOpening' | 'dashboard';
function estimateSeconds(business: BusinessDraft, setup: SetupDraft) { return Math.min(90, Math.max(24, 18 + business.products.length * 5 + setup.connectedPlatforms.length * 2 + Math.ceil(business.description.length / 90))); }
function getStage(ratio: number) { if (ratio < 0.22) return 1; if (ratio < 0.46) return 2; if (ratio < 0.7) return 3; if (ratio < 0.9) return 4; return 5; }
function BrandMark() { return <div className="brand-mark"><span className="brand-icon">MP</span><span>Burma MarketPilot</span><i /></div>; }
function Chip({ active, label, onClick }: { active: boolean; label: string; onClick: () => void }) { return <button type="button" className={`chip ${active ? 'chip-active' : ''}`} onClick={onClick}>{label}</button>; }
export default function App() {
  const [screen, setScreen] = useState<AppScreen>('signup');
  const [business, setBusiness] = useState<BusinessDraft>(initialBusiness);
  const [setup, setSetup] = useState<SetupDraft>(initialSetup);
  const [analysisStage, setAnalysisStage] = useState(1);
  const [analysisRemaining, setAnalysisRemaining] = useState(0);
  const [analysisTotal, setAnalysisTotal] = useState(0);
  const [analysisReady, setAnalysisReady] = useState(false);
  const progress = useMemo(() => { if (screen === 'signup') return 12; if (screen === 'step1') return 48; if (screen === 'step2') return 82; if (screen === 'analyzing') return Math.min(100, 82 + (analysisTotal ? ((analysisTotal - analysisRemaining) / analysisTotal) * 18 : 0)); return 100; }, [analysisRemaining, analysisTotal, screen]);
  useEffect(() => { if (screen !== 'analyzing' || analysisReady) return undefined; const timer = window.setInterval(() => { setAnalysisRemaining((current) => { const next = Math.max(0, current - 1); setAnalysisStage(getStage(analysisTotal ? (analysisTotal - next) / analysisTotal : 1)); if (next === 0) setAnalysisReady(true); return next; }); }, 1000); return () => window.clearInterval(timer); }, [analysisReady, analysisTotal, screen]);
  function toggle(list: string[], value: string) { return list.includes(value) ? list.filter((item) => item !== value) : [...list, value]; }
  function startAnalysis() { const seconds = estimateSeconds(business, setup); setAnalysisStage(1); setAnalysisRemaining(seconds); setAnalysisTotal(seconds); setAnalysisReady(false); setScreen('analyzing'); }
  const product = business.products[0];
  return <div className="app-shell"><div className="progress-track"><span style={{ width: `${progress}%` }} /></div><div className="ambient ambient-one" /><div className="ambient ambient-two" />
    {screen === 'signup' ? <main className="signup-page"><BrandMark /><section className="signup-layout"><div className="hero-copy"><span className="eyebrow">Myanmar business AI command center</span><h1>Build your marketing direction from Business DNA.</h1><p>Set up your business data once, then watch MarketPilot analyze it with a premium animated flow.</p><div className="metric-row"><div><b>2-Step</b><span>Onboarding</span></div><div><b>AI Flow</b><span>Animated analysis</span></div><div><b>Premium</b><span>3D SaaS UI</span></div></div></div><section className="auth-card glass"><div className="card-head center"><span className="mini-orbit">o</span><h2>Start Your MarketPilot Journey</h2><p>Build your Business DNA and run the AI analysis flow.</p></div><button className="primary-btn full" type="button" onClick={() => setScreen('step1')}>Start Setup</button></section></section></main> : null}
    {screen === 'step1' ? <main className="page-container"><Header step="Step 1 of 2" title="Business DNA Setup" subtitle="Business Identity and Product Data" /><section className="panel glass with-line"><div className="section-head"><div><h2>Business Identity</h2><p>Tell MarketPilot what your business is.</p></div><span className="pill-soft">Core DNA</span></div><div className="grid-two"><label className="field"><span className="field-label">Business Name</span><input value={business.businessName} onChange={(event) => setBusiness({ ...business, businessName: event.target.value })} /></label><div className="field"><span className="field-label">Industry Category</span><div className="chip-row">{categories.map((item) => <Chip key={item} label={item} active={business.category === item} onClick={() => setBusiness({ ...business, category: item })} />)}</div></div></div><label className="field"><span className="field-label">Business Description</span><textarea value={business.description} onChange={(event) => setBusiness({ ...business, description: event.target.value })} /></label></section><section className="panel glass with-line secondary-line"><div className="section-head"><div><h2>Product Universe</h2><p>Add the product that the AI should analyze.</p></div><span className="pill-soft">1 item</span></div><div className="grid-two"><label className="field"><span className="field-label">Product Name</span><input value={product.name} onChange={(event) => setBusiness({ ...business, products: [{ ...product, name: event.target.value }] })} /></label><label className="field"><span className="field-label">Price</span><input value={product.price} onChange={(event) => setBusiness({ ...business, products: [{ ...product, price: event.target.value }] })} /></label><label className="field"><span className="field-label">Category</span><input value={product.category} onChange={(event) => setBusiness({ ...business, products: [{ ...product, category: event.target.value }] })} /></label><label className="field"><span className="field-label">Unique Selling Point</span><input value={product.usp} onChange={(event) => setBusiness({ ...business, products: [{ ...product, usp: event.target.value }] })} /></label></div></section><BottomNav backLabel="Back" nextLabel="Next" onBack={() => setScreen('signup')} onNext={() => setScreen('step2')} /></main> : null}
    {screen === 'step2' ? <main className="page-container step-two"><Header step="Step 2 of 2" title="Business DNA Setup" subtitle="Channels and Goals" /><section className="panel glass platform-panel"><div className="section-head"><div><h2>Platform Integrations</h2><p>Select the channels your business uses.</p></div></div><div className="platform-grid">{platforms.map((platform) => <button key={platform} className={`platform-card ${setup.connectedPlatforms.includes(platform) ? 'connected' : ''}`} type="button" onClick={() => setSetup({ ...setup, connectedPlatforms: toggle(setup.connectedPlatforms, platform) })}><span className="platform-icon">{platform.slice(0, 1)}</span><span><b>{platform}</b><small>{setup.connectedPlatforms.includes(platform) ? 'Connected' : 'Connect account'}</small></span><em>{setup.connectedPlatforms.includes(platform) ? 'on' : 'Connect'}</em></button>)}</div></section><section className="panel glass"><div className="section-head"><div><h2>Posting Habits and Goals</h2><p>Help us tailor your AI content calendar pacing.</p></div></div><div className="preference-block"><strong>Posting frequency</strong><div className="chip-row">{frequencies.map((item) => <Chip key={item} label={item} active={setup.postingFrequency === item} onClick={() => setSetup({ ...setup, postingFrequency: item })} />)}</div></div><div className="preference-block"><strong>Primary AI assistance needed</strong><div className="chip-row">{assistanceOptions.map((item) => <Chip key={item} label={item} active={setup.assistance.includes(item)} onClick={() => setSetup({ ...setup, assistance: toggle(setup.assistance, item) })} />)}</div></div></section><section className="ready-note"><span>*</span><p><b>Almost Ready</b><br />Press Complete Setup to send your Business DNA into the AI analysis animation.</p></section><BottomNav backLabel="Back to Step 1" nextLabel="Complete Setup" onBack={() => setScreen('step1')} onNext={startAnalysis} /></main> : null}
    {screen === 'analyzing' ? <AnalysisLoadingPage stage={analysisStage} remaining={analysisRemaining} ready={analysisReady} saving={false} business={business} setup={setup} onOpen={() => setScreen('dashboardOpening')} /> : null}
    {screen === 'dashboardOpening' || screen === 'dashboard' ? <DashboardExperience business={business} setup={setup} opening={screen === 'dashboardOpening'} onOpened={() => setScreen('dashboard')} onEdit={() => setScreen('step1')} /> : null}
  </div>;
}
function Header({ step, title, subtitle }: { step: string; title: string; subtitle: string }) { return <header className="page-header"><BrandMark /><span className="eyebrow">{step} - {subtitle}</span><h1>{title}</h1><p>Premium, calm, human-made UI for Myanmar online business owners.</p></header>; }
function BottomNav({ backLabel, nextLabel, onBack, onNext }: { backLabel: string; nextLabel: string; onBack: () => void; onNext: () => void }) { return <nav className="bottom-nav"><button className="ghost-btn" type="button" onClick={onBack}>{backLabel}</button><button className="primary-btn" type="button" onClick={onNext}>{nextLabel}</button></nav>; }
